version: '{build}'
image: 
 - Visual Studio 2019
configuration: Release
pull_requests:
  do_not_increment_build_number: true
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
branches:
  only:
  - master
clone_depth: 1
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\Build.ps1
test_script:
- ps: .\run-sonar.ps1
artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet
- path: .\artifacts\**\*.xml
  name: xUnit Test Results
deploy:
- provider: NuGet
  name: nuget_release
  api_key:
    secure: 8CQ2rd7juz6iTAHi4mPTDOsUrsjhvKxTUqJCaz/GQimnzX0a5f0BAfhm7+lwOYGq
  on:
    appveyor_repo_tag: true